baseurl = "https://example.org/"
title = "Wonder Tiki Tattoo Studio"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "A website for a tatto studio in Luino, Italy"
  copyright = "&copy;2021 billiboi"
  sidebarAbout = [
   "Based in Luino since 2019."
   "Resident Tattoo artist: La Dany."
   "Old school, Japanese and Chicano styles."

  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Contatti"
  url = "contact/"

  [params.social]
  facebook      = "full page or profile url in facebook"
  instagram     = "full profile url in instagram"
