baseurl = "https://example.org/"
title = "Wonder Tiki Tattoo Studio"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "violet"
  description = "A website for a tattoo studio in Luino (Va) - Italy"
  copyright = "&copy;2016 billiboi"
  sidebarAbout = [
    "Via Confalonieri 14, 21016, Luino - 392 119  3962"
    "Lunedì: 09 - 12.00 / 14.00 - 19.00"
    "Martedì: 09 - 12.00 / 14.00 - 19.00"
    "Mercoledì: 09 - 12.00 / 14.00 - 19.00"
    "Giovedì: 09 - 12.00 / 14.00 - 19.00"
    "Venerdì: 09 - 12.00 / 14.00 - 19.00"
    "Sabato e Domenica - Chiuso"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "vdauria94@gmail.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  facebook      = "https://www.facebook.com/wondertikitattoo/"
  instagram     = "https://www.instagram.com/wondertikitattoo/"
  whatsapp      = "wa.me service link"
